const clearedApi = (name) => () =>
  Promise.reject(new Error(`${name} 旧平台接口已清空，请按新文档重新接入`))

export const loginApi = clearedApi('loginApi')
export const uploadPlatformFile = clearedApi('uploadPlatformFile')

export const getOverview = clearedApi('getOverview')
export const getTrend = clearedApi('getTrend')
export const getRealtimeOrders = clearedApi('getRealtimeOrders')
export const getRecentUpdates = clearedApi('getRecentUpdates')

export const getTenantList = clearedApi('getTenantList')
export const addTenant = clearedApi('addTenant')
export const editTenant = clearedApi('editTenant')
export const deleteTenant = clearedApi('deleteTenant')
export const changeTenantStatus = clearedApi('changeTenantStatus')
export const rechargeTenant = clearedApi('rechargeTenant')
export const resetTenantPassword = clearedApi('resetTenantPassword')
export const getTenantDetail = clearedApi('getTenantDetail')
export const getTenantUserList = clearedApi('getTenantUserList')
export const getTenantUserMenus = clearedApi('getTenantUserMenus')
export const addTenantUser = clearedApi('addTenantUser')
export const editTenantUser = clearedApi('editTenantUser')
export const changeTenantUserStatus = clearedApi('changeTenantUserStatus')
export const resetTenantUserPassword = clearedApi('resetTenantUserPassword')
export const deleteTenantUser = clearedApi('deleteTenantUser')

export const getVipList = clearedApi('getVipList')
export const addVip = clearedApi('addVip')
export const editVip = clearedApi('editVip')
export const changeVipStatus = clearedApi('changeVipStatus')
export const deleteVip = clearedApi('deleteVip')
export const getVipTotal = clearedApi('getVipTotal')

export const getOrderList = clearedApi('getOrderList')
export const getOrderTotal = clearedApi('getOrderTotal')

export const getCraftList = clearedApi('getCraftList')
export const addCraft = clearedApi('addCraft')
export const editCraft = clearedApi('editCraft')
export const changeCraftStatus = clearedApi('changeCraftStatus')
export const deleteCraft = clearedApi('deleteCraft')
